import { Lora } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "sonner";


export const metadata = {
  title: "Advivid AI",
  description: "Generated by create next app",
};

const lora = Lora({subsets: ["latin"]})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={lora.className}>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
